# Utilisation de l'image officielle Node.js
FROM node:18

# Définition du répertoire de travail dans le conteneur
WORKDIR /app

# Copie des fichiers package.json et package-lock.json avant d'installer les dépendances
COPY package.json package-lock.json ./

# Installation des dépendances avec npm
RUN npm install --production

# Copie du reste des fichiers du projet
COPY . .

# Exposition du port 5000 pour le backend
EXPOSE 5000

# Commande pour démarrer le serveur
CMD ["npm", "run", "start"]
